Repository DVdmitry/naakcii, pull requests merged in 2018-04, with the labels that each got.

#9 NAS-28: Autotest fot first page
  tests/e2e/.gitignore
  tests/e2e/configs/data/enviroment.js
  tests/e2e/package.json
  tests/e2e/protractor-conf.js
  tests/e2e/step_definitions/navigationSteps.js
  tests/e2e/step_definitions/page_steps/commonPageSteps.js
  tests/e2e/step_definitions/page_steps/homePageSteps.js
  tests/e2e/support/objects/pages/homePage.js
  tests/e2e/support/objects/pages/page.js
Labels: autotests

#10 NAS-23- data-model
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/by/naakcii/repository/RepositoryApplication.java
  src/main/java/by/naakcii/repository/dao/ActionDao.java
  src/main/java/by/naakcii/repository/dao/CategoryDao.java
  src/main/java/by/naakcii/repository/dao/ChainDao.java
  src/main/java/by/naakcii/repository/dao/GenericDao.java
  src/main/java/by/naakcii/repository/dao/ProductDao.java
  src/main/java/by/naakcii/repository/dao/ProductInfoDao.java
  src/main/java/by/naakcii/repository/dao/SubcategoryDao.java
  src/main/java/by/naakcii/repository/dao/impl/ActionDaoImpl.java
  src/main/java/by/naakcii/repository/dao/impl/CategoryDaoImpl.java
  src/main/java/by/naakcii/repository/dao/impl/ChainDaoImpl.java
  src/main/java/by/naakcii/repository/dao/impl/ProductDaoImpl.java
  src/main/java/by/naakcii/repository/dao/impl/ProductInfoDaoImpl.java
  src/main/java/by/naakcii/repository/dao/impl/SubcategoryDaoImpl.java
  src/main/java/by/naakcii/repository/model/Action.java
  src/main/java/by/naakcii/repository/model/Category.java
  src/main/java/by/naakcii/repository/model/Chain.java
  src/main/java/by/naakcii/repository/model/NamingStrategy.java
  src/main/java/by/naakcii/repository/model/Product.java
  src/main/java/by/naakcii/repository/model/ProductInfo.java
  src/main/java/by/naakcii/repository/model/Subcategory.java
  src/main/java/by/naakcii/repository/model/package-info.java
  src/main/resources/application.properties
  src/test/java/by/naakcii/repository/RepositoryApplicationTests.java
Labels: data base

#13 Актуализирован макет главной страницы.
  features/00_макеты/главная_страница.png
Labels: layouts

#14 Фиче-файлы для функциональности выбора торговых сетей
  features/00_макеты/главная_страница.png
  features/01_знакомство_с_сервисом/00_структура_страницы/01_главная_страница.png
  features/01_знакомство_с_сервисом/00_структура_страницы/02_главная_страница.json
  features/01_знакомство_с_сервисом/01_переход_на_главную_страницу.feature
  features/02_формирование_списка_покупок/00_структура_страницы/01_формирование_списка_покупок.png
  features/02_формирование_списка_покупок/00_структура_страницы/02_формирование_списка_покупок.json
  features/02_формирование_списка_покупок/02_переход_к_формированию_списка.feature
  features/02_формирование_списка_покупок/03_выбор_сетей.feature
  features/02_формирование_списка_покупок/04_плавная_подгрузка.feature
Labels: feature files

#17 Chain selection test
  README.md
  features/00_макеты/главная_страница.png
  features/01_знакомство_с_сервисом/00_структура_страницы/01_главная_страница.png
  features/01_знакомство_с_сервисом/00_структура_страницы/02_главная_страница.json
  features/01_знакомство_с_сервисом/01_переход_на_главную_страницу.feature
  features/02_формирование_списка_покупок/00_структура_страницы/01_формирование_списка_покупок.png
  features/02_формирование_списка_покупок/00_структура_страницы/02_формирование_списка_покупок.json
  features/02_формирование_списка_покупок/02_переход_к_формированию_списка.feature
  features/02_формирование_списка_покупок/03_выбор_сетей.feature
  features/02_формирование_списка_покупок/04_плавная_подгрузка.feature
  tests/e2e/.gitignore
  tests/e2e/README.md
  tests/e2e/configs/protractor-conf.js
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/protractor-conf.js
  tests/e2e/step_definitions/navigationSteps.js
  tests/e2e/step_definitions/page_steps/catalogPageSteps.js
  tests/e2e/step_definitions/page_steps/commonPageSteps.js
  tests/e2e/step_definitions/page_steps/homePageSteps.js
  tests/e2e/support/helpers/helper.js
  tests/e2e/support/objects/pageFactory.js
  tests/e2e/support/objects/pages/catalogPage.js
  tests/e2e/support/objects/pages/homePage.js
  tests/e2e/support/objects/pages/page.js
  tests/e2e/support/world.js
Labels: autotests

#19 Выбор торговых сетей
  README.md
  features/00_макеты/главная_страница.png
  features/01_знакомство_с_сервисом/00_структура_страницы/01_главная_страница.png
  features/01_знакомство_с_сервисом/00_структура_страницы/02_главная_страница.json
  features/01_знакомство_с_сервисом/01_переход_на_главную_страницу.feature
  features/02_формирование_списка_покупок/00_структура_страницы/01_формирование_списка_покупок.png
  features/02_формирование_списка_покупок/00_структура_страницы/02_формирование_списка_покупок.json
  features/02_формирование_списка_покупок/02_переход_к_формированию_списка.feature
  features/02_формирование_списка_покупок/03_выбор_сетей.feature
  features/02_формирование_списка_покупок/04_плавная_подгрузка.feature
  tests/e2e/.gitignore
  tests/e2e/README.md
  tests/e2e/configs/protractor-conf.js
  tests/e2e/package-lock.json
  tests/e2e/package.json
  tests/e2e/protractor-conf.js
  tests/e2e/step_definitions/navigationSteps.js
  tests/e2e/step_definitions/page_steps/catalogPageSteps.js
  tests/e2e/step_definitions/page_steps/commonPageSteps.js
  tests/e2e/step_definitions/page_steps/homePageSteps.js
  tests/e2e/support/helpers/helper.js
  tests/e2e/support/objects/pageFactory.js
  tests/e2e/support/objects/pages/catalogPage.js
  tests/e2e/support/objects/pages/homePage.js
  tests/e2e/support/objects/pages/page.js
  tests/e2e/support/world.js
Labels: enhancement

#21 Исправление опечаток и текста на фильтре сетей
  features/02_формирование_списка_покупок/03_выбор_сетей.feature
  features/02_формирование_списка_покупок/04_плавная_подгрузка.feature
Labels: defect

#22 Фронт для выбора категорий товаров
  front/src/app/foods-page/foods-category/foods-category.component.css
  front/src/app/foods-page/foods-category/foods-category.component.html
  front/src/app/foods-page/foods-category/foods-category.component.ts
  front/src/app/foods-page/foods-food-list/foods-food-card/foods-food-card.component.html
  front/src/app/foods-page/foods-food-list/foods-food-list.component.html
  front/src/app/foods-page/foods-page.component.css
  front/src/app/foods-page/foods-page.component.html
  front/src/app/foods-page/foods-page.component.ts
  front/src/app/foods-page/foods-storage-list/foods-storage-list.component.css
  front/src/app/foods-page/foods-storage-list/foods-storage-list.component.ts
  front/src/app/foods-page/foods-subCategory/foods-subCategory.component.css
  front/src/app/foods-page/foods-subCategory/foods-subCategory.component.html
  front/src/app/foods-page/foods-subCategory/foods-subCategory.component.ts
  front/src/app/foods-page/foods-total-items/foods-total-items.component.css
  front/src/app/foods-page/foods-total-items/foods-total-items.component.html
  front/src/app/foods-page/foods-total-items/foods-total-items.component.ts
  front/src/app/home-page/home-slider/home-slider.component.css
  front/src/app/home-page/home-steps/home-steps.component.css
  front/src/assets/images/Category/sprites/ac_unit.svg
  front/src/assets/images/Category/sprites/cake.svg
  front/src/assets/images/Category/sprites/child_care.svg
  front/src/assets/images/Category/sprites/filter_drama.svg
  front/src/assets/images/Category/sprites/free_breakfast.svg
  front/src/assets/images/Category/sprites/kitchen.svg
  front/src/assets/images/Category/sprites/local_drink.svg
  front/src/assets/images/Category/sprites/local_pizza.svg
  front/src/assets/images/Category/sprites/restaurant_menu.svg
  front/src/assets/images/Category/sprites/room_service.svg
  front/src/assets/images/Category/sprites/spa.svg
  front/src/index.html
Labels: front

#23 Фича-файл для выбора категории товаров
  features/02_формирование_списка_покупок/05_выбор_категории_товаров.feature
Labels: feature files

#24 Выбор категорий товаров
  features/02_формирование_списка_покупок/05_выбор_категории_товаров.feature
  front/src/app/foods-page/foods-category/foods-category.component.css
  front/src/app/foods-page/foods-category/foods-category.component.html
  front/src/app/foods-page/foods-category/foods-category.component.ts
  front/src/app/foods-page/foods-food-list/foods-food-card/foods-food-card.component.css
  front/src/app/foods-page/foods-food-list/foods-food-card/foods-food-card.component.html
  front/src/app/foods-page/foods-food-list/foods-food-list.component.html
  front/src/app/foods-page/foods-page.component.css
  front/src/app/foods-page/foods-page.component.html
  front/src/app/foods-page/foods-page.component.ts
  front/src/app/foods-page/foods-storage-list/foods-storage-list.component.css
  front/src/app/foods-page/foods-storage-list/foods-storage-list.component.ts
  front/src/app/foods-page/foods-subCategory/foods-subCategory.component.css
  front/src/app/foods-page/foods-subCategory/foods-subCategory.component.html
  front/src/app/foods-page/foods-subCategory/foods-subCategory.component.ts
  front/src/app/foods-page/foods-total-items/foods-total-items.component.css
  front/src/app/foods-page/foods-total-items/foods-total-items.component.html
  front/src/app/foods-page/foods-total-items/foods-total-items.component.ts
  front/src/app/home-page/home-slider/home-slider.component.css
  front/src/app/home-page/home-steps/home-steps.component.css
  front/src/assets/images/Category/sprites/ac_unit.svg
  front/src/assets/images/Category/sprites/cake.svg
  front/src/assets/images/Category/sprites/child_care.svg
  front/src/assets/images/Category/sprites/filter_drama.svg
  front/src/assets/images/Category/sprites/free_breakfast.svg
  front/src/assets/images/Category/sprites/kitchen.svg
  front/src/assets/images/Category/sprites/local_drink.svg
  front/src/assets/images/Category/sprites/local_pizza.svg
  front/src/assets/images/Category/sprites/restaurant_menu.svg
  front/src/assets/images/Category/sprites/room_service.svg
  front/src/assets/images/Category/sprites/spa.svg
  front/src/assets/images/Category/sprites/спрайт здоровое питание .svg
  front/src/index.html
Labels: enhancement
